// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace libraryManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219000920_CustomersData3")]
    partial class CustomersData3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAwardWinner")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Edition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<long>("ISBN")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublishedDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BranchId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Librarian")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 4,
                            Email = "cvance@outlook.com",
                            FirstName = "Chloe",
                            LastName = "Vance",
                            PhoneNumber = "6045550104"
                        },
                        new
                        {
                            CustomerId = 5,
                            Email = "d.park@gmail.com",
                            FirstName = "Daniel",
                            LastName = "Park",
                            PhoneNumber = "7785550105"
                        },
                        new
                        {
                            CustomerId = 6,
                            Email = "elena.rod@provider.net",
                            FirstName = "Elena",
                            LastName = "Rodriguez",
                            PhoneNumber = "6045550106"
                        },
                        new
                        {
                            CustomerId = 7,
                            Email = "fwright@techmail.com",
                            FirstName = "Felix",
                            LastName = "Wright",
                            PhoneNumber = "6045550107"
                        },
                        new
                        {
                            CustomerId = 8,
                            Email = "g.kim@vancouver.ca",
                            FirstName = "Grace",
                            LastName = "Kim",
                            PhoneNumber = "7785550108"
                        },
                        new
                        {
                            CustomerId = 9,
                            Email = "hmiller@business.com",
                            FirstName = "Henry",
                            LastName = "Miller",
                            PhoneNumber = "6045550109"
                        },
                        new
                        {
                            CustomerId = 10,
                            Email = "izzy.chen@gmail.com",
                            FirstName = "Isabella",
                            LastName = "Chen",
                            PhoneNumber = "6045550110"
                        },
                        new
                        {
                            CustomerId = 11,
                            Email = "jack.p@outlook.com",
                            FirstName = "Jack",
                            LastName = "Peterson",
                            PhoneNumber = "7785550111"
                        },
                        new
                        {
                            CustomerId = 12,
                            Email = "k.ross@web.com",
                            FirstName = "Katherine",
                            LastName = "Ross",
                            PhoneNumber = "6045550112"
                        },
                        new
                        {
                            CustomerId = 13,
                            Email = "liam.m@email.org",
                            FirstName = "Liam",
                            LastName = "Murray",
                            PhoneNumber = "6045550113"
                        },
                        new
                        {
                            CustomerId = 14,
                            Email = "foster.mia@gmail.com",
                            FirstName = "Mia",
                            LastName = "Foster",
                            PhoneNumber = "7785550114"
                        },
                        new
                        {
                            CustomerId = 15,
                            Email = "n.brooks@provider.com",
                            FirstName = "Noah",
                            LastName = "Brooks",
                            PhoneNumber = "6045550115"
                        },
                        new
                        {
                            CustomerId = 16,
                            Email = "o.grant@service.net",
                            FirstName = "Olivia",
                            LastName = "Grant",
                            PhoneNumber = "6045550116"
                        },
                        new
                        {
                            CustomerId = 17,
                            Email = "p.walsh@icloud.com",
                            FirstName = "Peter",
                            LastName = "Walsh",
                            PhoneNumber = "7785550117"
                        },
                        new
                        {
                            CustomerId = 18,
                            Email = "q.taylor@gmail.com",
                            FirstName = "Quinn",
                            LastName = "Taylor",
                            PhoneNumber = "6045550118"
                        },
                        new
                        {
                            CustomerId = 19,
                            Email = "ryan.s@vpl.ca",
                            FirstName = "Ryan",
                            LastName = "Singh",
                            PhoneNumber = "6045550119"
                        },
                        new
                        {
                            CustomerId = 20,
                            Email = "s.bennett@mail.com",
                            FirstName = "Sophie",
                            LastName = "Bennett",
                            PhoneNumber = "7785550120"
                        });
                });

            modelBuilder.Entity("Book", b =>
                {
                    b.HasOne("Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId");

                    b.HasOne("Branch", "Branch")
                        .WithMany("Books")
                        .HasForeignKey("BranchId");

                    b.Navigation("Author");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Branch", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
